name: Testing

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade sentry-sdk
          pip install --upgrade coverage
          pip install --pre gql[all]
          pip install -r src/requirements.txt
      - name: Run Tests
        run: python -m unittest test/test_pubfinder.py
      - name: "Convert coverage"
        run: "coverage run -m unittest discover"