name: Testing

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  package:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade sentry-sdk
          pip install --pre gql[all]
          pip install -r src/requirements.txt
      - name: Run Tests
        run: python -m unittest test/test_pubfinder.py
      - name: Combine coverage
        run: |
          python -m coverage combine
          python -m coverage xml
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
      - name: Upload coverage to Codecov
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
        uses: "codecov/codecov-action@v2"
        with:
          fail_ci_if_error: true