name: Testing

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade sentry-sdk
          pip install --pre gql[all]
          pip install -r src/requirements.txt
      - name: Run Tests
        run: python -m unittest test/test_pubfinder.py
      - name: Upload coverage data
        uses: "actions/upload-artifact@v2"
        with:
          name: coverage-data
          path: ".coverage.*"
          if-no-files-found: ignore

  coverage:
    runs-on: "ubuntu-latest"
    needs: tests

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"  # Use latest, so it understands all syntax.

      - name: "Install Coverage.py"
        run: "python -m pip install --upgrade coverage[toml]"

      - name: "Download coverage data"
        uses: actions/download-artifact@v2
        with:
          name: coverage-data

      - run: python -m coverage combine
      - run: python -m coverage html --skip-covered --skip-empty

      - name: Upload coverage report
        uses: "actions/upload-artifact@v2"
        with:
          name: html-report
          path: htmlcov

      - run: python -m coverage report --fail-under=100