name: Testing

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  package:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade sentry-sdk
          pip install gql[all]==3.0.0b0
          pip install -r src/requirements.txt
      - name: Run Tests
        run: python -m unittest test/test_pubfinder.py
